"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowUpRight, Check, CircleHelp, Copy, Database, GitBranch, Network, ShieldCheck } from "lucide-react";
import { anomalies, etfs, formatAum, similarity } from "@/lib/demo-data";

export function ETFDetail({isin}:{isin:string}){
  const etf=etfs.find(e=>e.isin===isin)??etfs[0]; const [tab,setTab]=useState("Overview"); const [copied,setCopied]=useState(false);
  const similar=useMemo(()=>etfs.filter(e=>e.isin!==etf.isin).map(e=>({etf:e,...similarity(etf,e)})).sort((a,b)=>b.score-a.score).slice(0,5),[etf]);
  const issues=anomalies.filter(a=>a.isin===etf.isin);
  const copy=()=>{navigator.clipboard?.writeText(etf.isin);setCopied(true);setTimeout(()=>setCopied(false),1200)};
  const tabs=["Overview","Listings","Fund characteristics","Similar ETFs","Anomalies","Data provenance","Raw record"];
  return <div className="mx-auto max-w-[1500px]">
    <Link href="/explorer" className="inline-flex items-center gap-2 text-xs text-[var(--muted)] hover:text-[var(--ink)]"><ArrowLeft size={14}/>Back to explorer</Link>
    <div className="mt-6 flex flex-col justify-between gap-6 xl:flex-row xl:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-[var(--accent-soft)] px-2 py-1 text-[10px] font-semibold text-[var(--accent)]">{etf.assetClass}</span><span className="rounded border hairline px-2 py-1 text-[10px] text-[var(--muted)]">UCITS</span>{issues.length>0&&<span className="rounded bg-red-50 px-2 py-1 text-[10px] text-red-700">{issues.length} anomaly</span>}</div><h1 className="mt-4 max-w-4xl text-3xl font-semibold tracking-[-.045em] lg:text-4xl">{etf.name}</h1><div className="mt-3 flex items-center gap-3 text-xs text-[var(--muted)]"><button onClick={copy} className="mono flex items-center gap-1.5">{etf.isin}{copied?<Check size={12}/>:<Copy size={12}/>}</button><span>·</span><span>{etf.issuer}</span><span>·</span><span>{etf.domicile} domiciled</span></div></div><div className="flex gap-2"><Link href={`/network?isin=${etf.isin}`} className="flex items-center gap-2 rounded-md border hairline bg-[var(--surface)] px-4 py-2.5 text-xs font-semibold"><Network size={14}/>Similarity map</Link><Link href={`/compare?isins=${etf.isin}`} className="rounded-md bg-[var(--ink)] px-4 py-2.5 text-xs font-semibold text-[var(--paper)]">Add to compare</Link></div></div>
    <div className="mt-8 grid overflow-hidden rounded-lg border hairline bg-[var(--surface)] sm:grid-cols-2 xl:grid-cols-6">{[
      ["Reported AUM",formatAum(etf.aum,etf.currency),"Atlas Data Feed"],["TER",`${etf.ter.toFixed(2)}%`,"Fund facts"],["Fund age",`${etf.age.toFixed(1)} years`,"Inception date"],["Listings",String(etf.exchanges.length),etf.exchanges[0]],["Freshness",`${etf.freshness} day${etf.freshness===1?"":"s"}`,"28 Aug 2026"],["Quality",`${etf.quality} / 100`,"6 dimensions"],
    ].map(([label,value,source])=><div key={label} className="border-b border-r hairline p-4 xl:border-b-0"><div className="text-[10px] uppercase tracking-wider text-[var(--muted)]">{label}</div><div className="metric-value mt-4 text-xl font-semibold">{value}</div><div className="mt-2 flex items-center gap-1 text-[9px] text-[var(--muted)]"><Database size={10}/>{source}</div></div>)}</div>
    <div className="mt-5 overflow-x-auto border-b hairline"><div className="flex min-w-max gap-6">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`border-b-2 px-1 py-3 text-xs ${tab===item?"border-[var(--accent)] font-semibold text-[var(--accent)]":"border-transparent text-[var(--muted)]"}`}>{item}</button>)}</div></div>
    <div className="mt-6">
      {tab==="Overview"&&<div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="rounded-lg border hairline bg-[var(--surface)] p-6"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Fund overview</h2><span className="text-[10px] text-[var(--muted)]">NORMALIZED ENTITY</span></div><dl className="mt-6 grid gap-px overflow-hidden rounded-md bg-[var(--line)] sm:grid-cols-2">{[["Issuer",etf.issuer],["Category",etf.category],["Benchmark",etf.benchmark],["Asset class",etf.assetClass],["Domicile",etf.domicile],["Fund currency",etf.currency],["Replication",etf.replication],["Distribution",etf.distribution]].map(([k,v])=><div key={k} className="bg-[var(--paper)] p-4"><dt className="text-[10px] uppercase tracking-wider text-[var(--muted)]">{k}</dt><dd className="mt-2 text-sm font-medium">{v}</dd></div>)}</dl></section><section className="rounded-lg border hairline bg-[var(--surface)] p-6"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-[var(--accent)]"/><h2 className="text-sm font-semibold">Quality score</h2></div><div className="mt-6 flex items-end gap-2"><span className="metric-value text-5xl font-semibold">{etf.quality}</span><span className="pb-1 text-sm text-[var(--muted)]">/ 100</span></div><div className="mt-6 space-y-3">{[["Identifier",100],["AUM",etf.aum===0?25:100],["Listings",100],["Freshness",Math.max(30,100-etf.freshness*2)],["Consistency",96],["Source confidence",95]].map(([k,v])=><div key={String(k)}><div className="mb-1 flex justify-between text-[10px]"><span>{k}</span><span className="mono">{v}</span></div><div className="h-1 rounded bg-[var(--line)]"><div className="h-full rounded bg-[var(--accent)]" style={{width:`${v}%`}}/></div></div>)}</div></section></div>}
      {tab==="Listings"&&<section className="overflow-hidden rounded-lg border hairline bg-[var(--surface)]"><table className="w-full min-w-[700px] text-left text-xs"><thead className="bg-[var(--paper)] text-[10px] uppercase tracking-wider text-[var(--muted)]"><tr><th className="px-5 py-3">Exchange</th><th className="px-4 py-3">Ticker</th><th className="px-4 py-3">Trading currency</th><th className="px-4 py-3">Listing date</th><th className="px-4 py-3">Validation</th></tr></thead><tbody>{etf.exchanges.map((exchange,i)=><tr key={exchange} className="border-t hairline"><td className="px-5 py-4 font-medium">{exchange}</td><td className="mono px-4 py-4">{etf.tickers[i]}</td><td className="px-4 py-4">{i%2?etf.currency:"EUR"}</td><td className="mono px-4 py-4">{`20${12+i}-0${i+2}-1${i}`}</td><td className="px-4 py-4 text-[var(--accent)]">✓ Exact key</td></tr>)}</tbody></table></section>}
      {tab==="Fund characteristics"&&<section className="rounded-lg border hairline bg-[var(--surface)] p-6"><h2 className="text-sm font-semibold">Normalized characteristics</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Asset class",etf.assetClass],["Category",etf.category],["Strategy",etf.category.includes("Climate")?"ESG":"Core"],["Benchmark / index",etf.benchmark],["Replication method",etf.replication],["Distribution policy",etf.distribution],["TER",`${etf.ter}%`],["Domicile",etf.domicile],["Fund currency",etf.currency]].map(([k,v])=><div key={k} className="rounded-md border hairline p-4"><div className="text-[10px] uppercase tracking-wider text-[var(--muted)]">{k}</div><div className="mt-2 text-sm font-medium">{v}</div></div>)}</div></section>}
      {tab==="Similar ETFs"&&<section className="rounded-lg border hairline bg-[var(--surface)]"><div className="border-b hairline p-5"><h2 className="text-sm font-semibold">Explainable nearest neighbors</h2><p className="mt-1 text-xs text-[var(--muted)]">Transparent weighted model; contributions sum to the score.</p></div>{similar.map(item=><Link href={`/etf/${item.etf.isin}`} key={item.etf.isin} className="grid gap-4 border-b hairline p-5 hover:bg-[var(--paper)] md:grid-cols-[1fr_90px_1.2fr]"><div><div className="text-sm font-medium">{item.etf.name}</div><div className="mono mt-1 text-[9px] text-[var(--muted)]">{item.etf.isin} · {item.etf.issuer}</div></div><div><div className="metric-value text-2xl font-semibold text-[var(--accent)]">{item.score}%</div><div className="text-[9px] text-[var(--muted)]">SIMILARITY</div></div><div className="flex flex-wrap gap-1.5">{item.contributions.slice(0,4).map(c=><span key={c.label} className="rounded bg-[var(--accent-soft)] px-2 py-1 text-[9px] text-[var(--accent)]">{c.label} +{c.points}%</span>)}</div></Link>)}</section>}
      {tab==="Anomalies"&&<section className="rounded-lg border hairline bg-[var(--surface)] p-6">{issues.length?issues.map(a=><div key={a.id} className="rounded-md border border-red-200 bg-red-50 p-5 text-red-950"><div className="flex items-center gap-2 text-xs font-semibold"><AlertTriangle size={15}/>{a.severity} · {a.title}</div><p className="mt-3 max-w-3xl text-sm leading-6">{a.explanation}</p><div className="mt-4 grid max-w-lg grid-cols-2 gap-4 text-xs"><div><span className="block text-[10px] uppercase text-red-500">Observed</span><span className="mt-1 block font-medium">{a.observed}</span></div><div><span className="block text-[10px] uppercase text-red-500">Expected</span><span className="mt-1 block font-medium">{a.expected}</span></div></div></div>):<div className="py-16 text-center"><Check className="mx-auto text-[var(--accent)]"/><h2 className="mt-3 text-sm font-semibold">No anomalies detected</h2><p className="mt-1 text-xs text-[var(--muted)]">All deterministic rules and the latest multivariate scan passed.</p></div>}</section>}
      {tab==="Data provenance"&&<section className="rounded-lg border hairline bg-[var(--surface)] p-6"><div className="flex items-center gap-2"><GitBranch size={16} className="text-[var(--accent)]"/><h2 className="text-sm font-semibold">Value-level lineage</h2></div><div className="mt-7 flex flex-col items-stretch gap-2 lg:flex-row lg:items-center">{["Synthetic provider","Allowlisted CSV","Polars normalize","Listing dedupe","ETF entity","Analytics"].map((step,i)=><div key={step} className="contents"><div className="flex-1 rounded-md border hairline bg-[var(--paper)] p-4"><div className="mono text-[9px] text-[var(--accent)]">0{i+1}</div><div className="mt-2 text-xs font-medium">{step}</div><div className="mt-1 text-[9px] text-[var(--muted)]">Verified</div></div>{i<5&&<span className="rotate-90 text-center text-[var(--muted)] lg:rotate-0">→</span>}</div>)}</div><div className="mt-8 grid gap-3 md:grid-cols-3">{[["AUM",formatAum(etf.aum,etf.currency),etf.provider],["TER",`${etf.ter}%`,"Synthetic fund facts"],["Listing count",String(etf.exchanges.length),"Normalized listing keys"]].map(([field,value,source])=><div key={field} className="rounded-md border hairline p-4"><div className="text-[10px] uppercase text-[var(--muted)]">{field}</div><div className="mt-2 text-xl font-semibold">{value}</div><div className="mt-3 text-[10px] text-[var(--muted)]">Source: {source}<br/>Snapshot: 2026-08-28</div></div>)}</div></section>}
      {tab==="Raw record"&&<section className="rounded-lg border hairline bg-[#111a21] p-6 text-[#dcefe9]"><div className="mb-4 flex items-center justify-between"><span className="mono text-xs">normalized_record.json</span><span className="rounded bg-white/10 px-2 py-1 text-[9px]">PUBLIC ALLOWLIST</span></div><pre className="overflow-auto text-[11px] leading-6">{JSON.stringify(etf,null,2)}</pre></section>}
    </div>
    <div className="mt-5 flex items-center gap-2 text-[10px] text-[var(--muted)]"><CircleHelp size={12}/>All values on this page are synthetic demonstrations, not investment data.<Link href="/architecture" className="ml-auto flex items-center gap-1 text-[var(--accent)]">Methodology <ArrowUpRight size={11}/></Link></div>
  </div>
}
