"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Check, Plus, Scale, X } from "lucide-react";
import { etfs, formatAum, similarity } from "@/lib/demo-data";

export function ETFCompare(){
  const [selected,setSelected]=useState([etfs[0].isin,etfs[2].isin,etfs[4].isin]);
  useEffect(()=>{const value=new URLSearchParams(window.location.search).get("isins");if(value){const valid=value.split(",").filter(i=>etfs.some(e=>e.isin===i));if(valid.length)setSelected(valid)}},[]);
  const items=selected.map(isin=>etfs.find(e=>e.isin===isin)!).filter(Boolean); const baseline=items[0];
  const summary=useMemo(()=>{if(items.length<2)return "Select at least two ETFs to generate a deterministic comparison.";const largest=[...items].sort((a,b)=>(b.aum||0)-(a.aum||0))[0];const smallest=[...items].sort((a,b)=>(a.aum||0)-(b.aum||0))[0];const ratio=(largest.aum||0)/Math.max(smallest.aum||1,1);return `${largest.name} has approximately ${ratio.toFixed(1)}× the reported AUM of ${smallest.name} but ${largest.exchanges.length<smallest.exchanges.length?"is listed on fewer":"has at least as many"} exchanges.`},[items]);
  const add=()=>{const next=etfs.find(e=>!selected.includes(e.isin));if(next&&selected.length<5)setSelected([...selected,next.isin])};
  const rows=[
    ["Reported AUM",(e:typeof etfs[0])=>formatAum(e.aum,e.currency)], ["Issuer",(e:typeof etfs[0])=>e.issuer], ["Asset class",(e:typeof etfs[0])=>e.assetClass], ["Fund currency",(e:typeof etfs[0])=>e.currency], ["TER",(e:typeof etfs[0])=>`${e.ter.toFixed(2)}%`], ["Age",(e:typeof etfs[0])=>`${e.age.toFixed(1)} years`], ["Exchange coverage",(e:typeof etfs[0])=>`${e.exchanges.length} listings`], ["Data freshness",(e:typeof etfs[0])=>`${e.freshness} days`], ["Quality score",(e:typeof etfs[0])=>`${e.quality} / 100`], ["Similarity to first",(e:typeof etfs[0])=>e.isin===baseline?.isin?"Baseline":`${similarity(baseline,e).score}%`], ["Replication",(e:typeof etfs[0])=>e.replication], ["Distribution",(e:typeof etfs[0])=>e.distribution],
  ] as const;
  return <div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--accent)]">ETF compare</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Meaningful differences, side by side</h1><p className="mt-2 text-sm text-[var(--muted)]">Compare two to five normalized funds with automatic highlights.</p></div><button disabled={selected.length>=5} onClick={add} className="flex items-center gap-2 rounded-md bg-[var(--ink)] px-4 py-2.5 text-xs font-semibold text-[var(--paper)] disabled:opacity-40"><Plus size={14}/>Add ETF</button></div>
    <div className="mt-7 rounded-lg border hairline bg-[var(--accent-soft)] p-5"><div className="flex items-start gap-3"><Scale size={18} className="mt-0.5 shrink-0 text-[var(--accent)]"/><div><div className="text-[10px] font-semibold uppercase tracking-wider text-[var(--accent)]">Deterministic summary</div><p className="mt-2 text-sm font-medium leading-6">{summary}</p><p className="mt-1 text-[10px] text-[var(--muted)]">Generated from normalized values. No LLM used.</p></div></div></div>
    <section className="mt-5 overflow-x-auto rounded-lg border hairline bg-[var(--surface)]"><table className="w-full min-w-[900px] table-fixed text-left text-xs"><thead><tr className="bg-[var(--paper)]"><th className="w-44 border-r hairline p-4 text-[10px] uppercase tracking-wider text-[var(--muted)]">Dimension</th>{items.map((e,i)=><th key={e.isin} className="border-r hairline p-4 align-top last:border-r-0"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 text-[9px] uppercase tracking-wider text-[var(--accent)]">ETF {String.fromCharCode(65+i)}</div><Link href={`/etf/${e.isin}`} className="text-sm font-semibold leading-5 hover:text-[var(--accent)]">{e.name}</Link><div className="mono mt-2 text-[9px] font-normal text-[var(--muted)]">{e.isin}</div></div><button aria-label="Remove ETF" disabled={selected.length<=2} onClick={()=>setSelected(selected.filter(x=>x!==e.isin))} className="text-[var(--muted)] disabled:opacity-20"><X size={14}/></button></div><select value={e.isin} onChange={event=>setSelected(selected.map((value,index)=>index===i?event.target.value:value))} className="mt-4 w-full rounded border hairline bg-[var(--surface)] p-2 text-[10px] outline-none">{etfs.filter(x=>x.isin===e.isin||!selected.includes(x.isin)).map(x=><option key={x.isin} value={x.isin}>{x.name}</option>)}</select></th>)}</tr></thead><tbody>{rows.map(([label,value])=>{const values=items.map(value);const different=new Set(values).size>1;return <tr key={label} className="border-t hairline"><th className="border-r hairline px-4 py-3 font-medium"><span className="flex items-center gap-2">{label}{different&&<span title="Meaningful difference" className="size-1.5 rounded-full bg-[var(--warning)]"/>}</span></th>{items.map((e,i)=><td key={e.isin} className={`border-r hairline px-4 py-3 last:border-r-0 ${different&&i===0?"bg-[var(--accent-soft)]/35":""}`}><span className="font-medium">{value(e)}</span>{label==="Quality score"&&e.quality>=95&&<Check size={12} className="ml-2 inline text-[var(--accent)]"/>}</td>)}</tr>})}</tbody></table></section>
    <div className="mt-3 text-[10px] text-[var(--muted)]">Orange markers indicate dimensions that differ across the selected funds. AUM is not converted across currencies.</div>
  </div>
}
