"use client";

import { useState } from "react";
import { ArrowRight, FileDiff, Minus, Plus } from "lucide-react";
import { etfs, snapshots } from "@/lib/demo-data";

export function HistoryDiff(){
  const [from,setFrom]=useState(snapshots[0].date);const [to,setTo]=useState(snapshots[2].date);const a=snapshots.find(x=>x.date===from)!;const b=snapshots.find(x=>x.date===to)!;
  const changed=etfs.slice(0,8).map((e,i)=>({isin:e.isin,name:e.name,field:i%3===0?"aum_millions":i%3===1?"listing_count":"ter",before:i%3===0?Math.round((e.aum||0)*.91):i%3===1?Math.max(1,e.exchanges.length-1):+(e.ter+.02).toFixed(2),after:i%3===0?e.aum:i%3===1?e.exchanges.length:e.ter}));
  return <div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--accent)]">Dataset time travel</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">What changed?</h1><p className="mt-2 text-sm text-[var(--muted)]">A Git-style diff for ETF entities, listings, and provider quality.</p></div><div className="flex items-center gap-2 rounded-md border hairline bg-[var(--surface)] p-2"><select value={from} onChange={e=>setFrom(e.target.value)} className="bg-transparent px-2 py-1 text-xs font-medium outline-none">{snapshots.map(s=><option key={s.date}>{s.date}</option>)}</select><ArrowRight size={14} className="text-[var(--muted)]"/><select value={to} onChange={e=>setTo(e.target.value)} className="bg-transparent px-2 py-1 text-xs font-medium outline-none">{snapshots.map(s=><option key={s.date}>{s.date}</option>)}</select></div></div>
    <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["ETF count Δ",b.etfs-a.etfs,`${a.etfs} → ${b.etfs}`],["Listing count Δ",b.listings-a.listings,`${a.listings} → ${b.listings}`],["AUM coverage Δ",+(b.coverage-a.coverage).toFixed(1),`${a.coverage}% → ${b.coverage}%`],["Changed ETFs",37,"field-level updates"],["Health Δ",b.health-a.health,`${a.health} → ${b.health}`]].map(([label,value,note])=><div key={String(label)} className="rounded-lg border hairline bg-[var(--surface)] p-4"><div className="text-[10px] uppercase tracking-wider text-[var(--muted)]">{String(label)}</div><div className={`metric-value mt-4 text-3xl font-semibold ${Number(value)>=0?"text-[var(--accent)]":"text-red-600"}`}>{Number(value)>=0?"+":""}{String(value)}{String(label).includes("coverage")?" pp":""}</div><div className="mt-1 text-[10px] text-[var(--muted)]">{String(note)}</div></div>)}</div>
    <section className="mt-5 overflow-hidden rounded-lg border hairline bg-[var(--surface)]"><div className="flex items-center justify-between border-b hairline p-5"><div className="flex items-center gap-2"><FileDiff size={16} className="text-[var(--accent)]"/><div><h2 className="text-sm font-semibold">Entity field changes</h2><p className="mt-1 text-xs text-[var(--muted)]">Representative changes from the selected snapshots</p></div></div><div className="flex gap-2 text-[9px]"><span className="rounded bg-green-50 px-2 py-1 text-green-700">+ 14 added</span><span className="rounded bg-red-50 px-2 py-1 text-red-700">− 0 removed</span><span className="rounded bg-amber-50 px-2 py-1 text-amber-700">~ 37 changed</span></div></div><div>{changed.map(item=><div key={item.isin} className="grid gap-3 border-b hairline p-4 last:border-0 md:grid-cols-[1.2fr_.45fr_1fr]"><div><div className="text-xs font-medium">{item.name}</div><div className="mono mt-1 text-[9px] text-[var(--muted)]">{item.isin}</div></div><div className="text-[10px] text-[var(--muted)]">{item.field}</div><div className="flex items-center gap-2 font-mono text-[10px]"><span className="rounded bg-red-50 px-2 py-1 text-red-700"><Minus size={9} className="mr-1 inline"/>{item.before}</span><ArrowRight size={10}/><span className="rounded bg-green-50 px-2 py-1 text-green-700"><Plus size={9} className="mr-1 inline"/>{item.after}</span></div></div>)}</div></section><p className="mt-3 text-[10px] text-[var(--muted)]">Changes can reflect source coverage or normalization updates and do not imply market events.</p>
  </div>
}
