"use client";

import { Activity, CheckCircle2, CircleAlert, Clock3, Database, ShieldCheck } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { providers, snapshots } from "@/lib/demo-data";

export function Observability(){
  const dimensions=[{name:"Completeness",score:98,copy:"Required analytical fields populated"},{name:"Freshness",score:96,copy:"Observation age against 14-day SLO"},{name:"Consistency",score:94,copy:"Cross-listing value agreement"},{name:"Uniqueness",score:99,copy:"Unique ISIN/exchange/ticker keys"},{name:"Validity",score:95,copy:"Format, range and date rules"}];
  return <div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--accent)]">Data observability</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Trust, quantified</h1><p className="mt-2 text-sm text-[var(--muted)]">Provider reliability, freshness, completeness, and schema health in one view.</p></div><div className="flex items-center gap-2 text-xs text-[var(--accent)]"><CheckCircle2 size={15}/>All critical contracts operating</div></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[340px_1fr]"><section className="rounded-lg border hairline bg-[var(--surface)] p-6"><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-[var(--accent)]"/><h2 className="text-sm font-semibold">Dataset health</h2></div><div className="mt-7 flex items-end gap-2"><span className="metric-value text-7xl font-semibold">96</span><span className="pb-2 text-lg text-[var(--muted)]">/ 100</span></div><div className="mt-3 inline-flex rounded-full bg-[var(--accent-soft)] px-2.5 py-1 text-[10px] font-semibold text-[var(--accent)]">HEALTHY · +2 SINCE PRIOR</div><div className="mt-7 space-y-4">{dimensions.map(d=><div key={d.name}><div className="mb-1.5 flex justify-between text-xs"><span>{d.name}</span><span className="mono">{d.score}</span></div><div className="h-1.5 rounded bg-[var(--line)]"><div className="h-full rounded bg-[var(--accent)]" style={{width:`${d.score}%`}}/></div><p className="mt-1 text-[9px] text-[var(--muted)]">{d.copy}</p></div>)}</div></section>
      <section className="rounded-lg border hairline bg-[var(--surface)] p-6"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold">Quality history</h2><p className="mt-1 text-xs text-[var(--muted)]">Three synthetic snapshots</p></div><span className="mono text-[10px] text-[var(--muted)]">SLO ≥ 92</span></div><div className="mt-6 h-[390px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={snapshots}><defs><linearGradient id="obs" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--accent)" stopOpacity={.3}/><stop offset="1" stopColor="var(--accent)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:10}}/><YAxis domain={[80,100]} axisLine={false} tickLine={false} tick={{fill:"var(--muted)",fontSize:10}}/><Tooltip contentStyle={{background:"var(--surface)",border:"1px solid var(--line)",borderRadius:8,fontSize:11}}/><Area type="monotone" dataKey="health" stroke="var(--accent)" fill="url(#obs)" strokeWidth={2}/><Area type="monotone" dataKey="coverage" stroke="#8aa0a4" fill="transparent" strokeDasharray="4 4"/></AreaChart></ResponsiveContainer></div></section></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[[Database,"Successful records","545","99.3%"],[CircleAlert,"Incomplete records","7","1.3%"],[Clock3,"Freshness","1.8d","median"],[Activity,"Duplicate rate","0.18%","1 key"],[CheckCircle2,"AUM coverage","98.7%","+2.6 pp"]].map(([Icon,label,value,note])=>{const Glyph=Icon as typeof Database;return <div key={String(label)} className="rounded-lg border hairline bg-[var(--surface)] p-4"><div className="flex items-center justify-between text-[10px] uppercase tracking-wider text-[var(--muted)]"><span>{String(label)}</span><Glyph size={14}/></div><div className="metric-value mt-5 text-2xl font-semibold">{String(value)}</div><div className="mt-1 text-[10px] text-[var(--accent)]">{String(note)}</div></div>})}</div>
    <section className="mt-5 rounded-lg border hairline bg-[var(--surface)]"><div className="flex flex-col justify-between gap-3 border-b hairline p-5 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold">Provider reliability</h2><p className="mt-1 text-xs text-[var(--muted)]">Operational quality of public/synthetic data feeds—not fund performance</p></div><span className="rounded border hairline px-2 py-1 text-[9px] text-[var(--muted)]">30% completeness · 25% freshness · 15% consistency · 10% uniqueness · 15% validity · 5% inverse anomaly rate</span></div><div className="grid gap-px bg-[var(--line)] md:grid-cols-2 xl:grid-cols-3">{providers.map(provider=><article key={provider.name} className="bg-[var(--surface)] p-5"><div className="flex items-start justify-between"><div><h3 className="text-sm font-semibold">{provider.name}</h3><div className="mt-1 text-[10px] text-[var(--muted)]">{provider.records} entity records</div></div><div className={`metric-value text-3xl font-semibold ${provider.score<85?"text-[var(--warning)]":"text-[var(--accent)]"}`}>{provider.score}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-[10px]"><div><span className="block text-[var(--muted)]">Freshness</span><strong className="mt-1 block">{provider.freshness}%</strong></div><div><span className="block text-[var(--muted)]">Complete</span><strong className="mt-1 block">{provider.completeness}%</strong></div><div><span className="block text-[var(--muted)]">Anomalies</span><strong className="mt-1 block">{provider.anomalies}</strong></div></div><div className="mt-4 h-1.5 rounded bg-[var(--paper)]"><div className={`h-full rounded ${provider.score<85?"bg-[var(--warning)]":"bg-[var(--accent)]"}`} style={{width:`${provider.score}%`}}/></div></article>)}</div></section>
  </div>
}
