"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ExternalLink, Filter, Network } from "lucide-react";
import { etfs, formatAum, similarity } from "@/lib/demo-data";

export function SimilarityNetwork(){
  const [selected,setSelected]=useState(etfs[0]); const [active,setActive]=useState(etfs[1]); const [threshold,setThreshold]=useState(52); const [issuer,setIssuer]=useState("");
  useEffect(()=>{const isin=new URLSearchParams(window.location.search).get("isin");const found=etfs.find(e=>e.isin===isin);if(found){setSelected(found);setActive(found)}},[]);
  const matches=useMemo(()=>etfs.filter(e=>e.isin!==selected.isin).map(e=>({etf:e,...similarity(selected,e)})).filter(x=>x.score>=threshold&&(!issuer||x.etf.issuer===issuer)).sort((a,b)=>b.score-a.score).slice(0,8),[selected,threshold,issuer]);
  const activeScore=active.isin===selected.isin?null:similarity(selected,active);
  const positions=[[50,12],[78,24],[88,51],[75,78],[48,88],[20,76],[11,47],[23,20]];
  return <div className="mx-auto max-w-[1500px]">
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--accent)]">Similarity map</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Navigate the ETF neighborhood</h1><p className="mt-2 text-sm text-[var(--muted)]">Every edge is a transparent weighted comparison—not a black box.</p></div><label className="flex items-center gap-3 rounded-md border hairline bg-[var(--surface)] px-3 py-2"><span className="text-[10px] uppercase text-[var(--muted)]">Central ETF</span><select value={selected.isin} onChange={e=>{const item=etfs.find(x=>x.isin===e.target.value)!;setSelected(item);setActive(item)}} className="max-w-64 bg-transparent text-xs font-medium outline-none">{etfs.map(e=><option key={e.isin} value={e.isin}>{e.name}</option>)}</select></label></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[1fr_320px]">
      <section className="relative min-h-[650px] overflow-hidden rounded-lg border hairline bg-[var(--surface)]">
        <div className="absolute inset-x-0 top-0 z-10 flex flex-wrap items-center justify-between gap-3 border-b hairline bg-[var(--surface)]/95 p-4"><div className="flex items-center gap-2 text-xs font-semibold"><Network size={15} className="text-[var(--accent)]"/>{matches.length+1} nodes · {matches.length} edges</div><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-[10px] text-[var(--muted)]"><Filter size={12}/>Issuer<select value={issuer} onChange={e=>setIssuer(e.target.value)} className="rounded border hairline bg-[var(--surface)] p-1.5 text-[10px]"><option value="">All</option>{[...new Set(etfs.map(e=>e.issuer))].map(i=><option key={i}>{i}</option>)}</select></label><label className="flex items-center gap-2 text-[10px] text-[var(--muted)]">Threshold <input type="range" min="20" max="90" value={threshold} onChange={e=>setThreshold(Number(e.target.value))} className="accent-[var(--accent)]"/><span className="mono w-7">{threshold}</span></label></div></div>
        <div className="absolute inset-0 top-16 bg-[radial-gradient(circle_at_center,var(--accent-soft)_0,transparent_46%)]">
          <svg className="absolute inset-0 h-full w-full" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden>{matches.map((m,i)=><line key={m.etf.isin} x1="50" y1="50" x2={positions[i][0]} y2={positions[i][1]} stroke="var(--accent)" strokeOpacity={Math.max(.18,m.score/120)} strokeWidth={Math.max(.12,m.score/280)} strokeDasharray={m.score<65?"1 1":"0"}/>)}</svg>
          <button onClick={()=>setActive(selected)} className="absolute left-1/2 top-1/2 z-10 grid size-32 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-2 border-[var(--accent)] bg-[var(--surface)] p-4 text-center shadow-xl"><span><span className="block text-[9px] uppercase tracking-wider text-[var(--accent)]">Central node</span><span className="mt-1 block text-xs font-semibold leading-4">{selected.name}</span><span className="mono mt-1 block text-[8px] text-[var(--muted)]">{selected.isin}</span></span></button>
          {matches.map((m,i)=><button key={m.etf.isin} onClick={()=>setActive(m.etf)} className={`absolute z-10 grid -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border bg-[var(--surface)] p-2 text-center shadow-md transition-transform hover:scale-110 ${active.isin===m.etf.isin?"border-[var(--accent)] ring-4 ring-[var(--accent-soft)]":"hairline"}`} style={{left:`${positions[i][0]}%`,top:`${positions[i][1]}%`,width:Math.max(74,Math.min(112,60+Math.log1p(m.etf.aum||0)*5)),height:Math.max(74,Math.min(112,60+Math.log1p(m.etf.aum||0)*5))}}><span><span className="block text-[9px] font-semibold leading-3">{m.etf.issuer.split(" ")[0]}</span><span className="mono mt-1 block text-[9px] text-[var(--accent)]">{m.score}%</span></span></button>)}
        </div><div className="absolute bottom-3 left-3 rounded border hairline bg-[var(--surface)]/90 px-3 py-2 text-[9px] text-[var(--muted)]">Node size → AUM · edge opacity → similarity · label → issuer</div>
      </section>
      <aside className="h-fit rounded-lg border hairline bg-[var(--surface)]"><div className="border-b hairline p-5"><div className="text-[9px] uppercase tracking-wider text-[var(--muted)]">Selected node</div><h2 className="mt-2 text-base font-semibold leading-5">{active.name}</h2><div className="mono mt-2 text-[9px] text-[var(--muted)]">{active.isin}</div></div><div className="grid grid-cols-2 gap-px bg-[var(--line)]"><div className="bg-[var(--surface)] p-4"><div className="text-[9px] uppercase text-[var(--muted)]">AUM</div><div className="mt-1 text-lg font-semibold">{formatAum(active.aum,active.currency)}</div></div><div className="bg-[var(--surface)] p-4"><div className="text-[9px] uppercase text-[var(--muted)]">Similarity</div><div className="mt-1 text-lg font-semibold text-[var(--accent)]">{activeScore?`${activeScore.score}%`:"Center"}</div></div></div>{activeScore&&<div className="p-5"><div className="text-[10px] font-semibold uppercase tracking-wider text-[var(--muted)]">Why it is similar</div><div className="mt-4 space-y-4">{activeScore.contributions.slice(0,6).map(c=><div key={c.label}><div className="mb-1 flex justify-between text-[10px]"><span>{c.label}</span><span className="mono text-[var(--accent)]">+{c.points}%</span></div><div className="h-1 rounded bg-[var(--line)]"><div className="h-full rounded bg-[var(--accent)]" style={{width:`${c.value*100}%`}}/></div></div>)}</div></div>}<div className="border-t hairline p-4"><Link href={`/etf/${active.isin}`} className="flex w-full items-center justify-center gap-2 rounded-md bg-[var(--ink)] px-4 py-2.5 text-xs font-semibold text-[var(--paper)]">Open ETF <ExternalLink size={12}/></Link>{active.isin!==selected.isin&&<button onClick={()=>{setSelected(active);setActive(active)}} className="mt-2 w-full rounded-md border hairline px-4 py-2.5 text-xs font-semibold">Re-center graph</button>}</div></aside>
    </div>
  </div>
}
